#!/bin/bash
#
# Copyright (C) 2009 Ken VanDine <kvandine@gnome.org>
#
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

package=$1 
workingDir=$HOME/source/gnome
cacheDir=$HOME/source/cache

if  [ $# -ne 1  ]
then
        echo "usage: gitprep PACKAGENAME"
        exit
else
        cd $workingDir
        cvc co $package
        cd $workingDir/$package
        cvc refresh
        echo Your source checkout can be found at $cacheDir/$package/git.gnome.org_"$package"_/git
        echo Your package checkout can be found at $workingDir/$package/
fi
